services:
  prabudda-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prabudda-portfolio
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Mount SSL certificates (will be created by ssl-setup.sh)
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./default-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      # Mount certbot webroot for renewals
      - ./certbot-webroot:/var/www/certbot:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - portfolio-network

  # Certbot service for automatic renewal
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    command: renew --webroot --webroot-path=/var/www/certbot --quiet
    profiles:
      - renewal
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
